In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Mutual Fund Dataset 2025.csv")

print(df.shape)
df.head()

(1797, 37)

,Funds,Fund Manager,Category,RupeeVestRating,AUM(in Rs. cr),ExpenseRatio (%),Fund Type,Inception Date,Benchmark Index,NAV,...,Avg. Maturity(in yrs),Mod. Duration(in yrs),Yield To Maturity (%),Alpha,Sharpe,Sortino,Beta,Standard Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,Unrated,860.1,1.94,Open Ended,25-Sep-23,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.93,-,7.39,8.27,1.58,2.28,1.2,7.5,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,24-Jun-13,CRISIL Dynamic Bond Index,21.5,...,6.85,-,7.35,3.5,3.72,6.7,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,Unrated,75.8,0.52,Open Ended,28-Dec-22,NIFTY 50 - TRI,13.45,...,-,-,-,1.51,0.47,0.71,0.99,13.9,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,Unrated,1254.2,2.08,Open Ended,30-Jun-23,BSE 500 - TRI,15.33,...,-,-,-,16.98,1.4,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305,1.78,Open Ended,30-Oct-14,BSE 500 - TRI,46.19,...,-,-,-,6.25,0.71,1,1.02,16.03,Equity : Multi Cap,1% on or before 12M

In [2]:
# Replacing missing symbols with NaN
df.columns = df.columns.str.strip()
df.replace(['-', ' - ', '--', 'NA', 'N/A'], np.nan, inplace=True)

In [3]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

In [4]:
percentage_columns = [
    'ExpenseRatio (%)',
    'Return (%)1 mo',
    'Return (%)3 mo',
    'Return (%)6 mo',
    'Return (%)1 yr',
    'Return (%)2 yrs',
    'Return (%)3 yrs',
    'Return (%)5 yrs',
    'Return (%)10 yrs',
    'Turnover Ratio (%)',
    'Large Cap(%)',
    'Mid Cap(%)',
    'Small Cap(%)',
    'Yield To Maturity (%)'
]

for col in percentage_columns:
    if col in df.columns:
        df[col] = df[col].str.replace('%', '', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [5]:
# Convert Inception Date to Datetime

df['Inception Date'] = pd.to_datetime(df['Inception Date'],errors='coerce')

/tmp/ipykernel_5389/2014724063.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Inception Date'] = pd.to_datetime(df['Inception Date'],errors='coerce')

In [6]:
# Convert Float Columns

float_columns = [
    'AUM(in Rs. cr)', 'ExpenseRatio (%)', 'NAV',
    '52 WeekHigh (NAV)', '52 WeekLow (NAV)',
    'Return (%)1 mo', 'Return (%)3 mo', 'Return (%)6 mo',
    'Return (%)1 yr', 'Return (%)2 yrs', 'Return (%)3 yrs',
    'Return (%)5 yrs', 'Return (%)10 yrs',
    'Turnover Ratio (%)', 'Avg. Market Cap(in Rs. cr)',
    'Large Cap(%)', 'Mid Cap(%)', 'Small Cap(%)',
    'Avg. Maturity(in yrs)', 'Mod. Duration(in yrs)',
    'Yield To Maturity (%)', 'Alpha', 'Sharpe',
    'Sortino', 'Beta', 'Standard Deviation'
]

for col in float_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [7]:
print(df.columns.tolist())

['Funds', 'Fund Manager', 'Category', 'RupeeVestRating', 'AUM(in Rs. cr)', 'ExpenseRatio (%)', 'Fund Type', 'Inception Date', 'Benchmark Index', 'NAV', '52 WeekHigh (NAV)', '52 WeekLow (NAV)', 'Return (%)1 mo', 'Return (%)3 mo', 'Return (%)6 mo', 'Return (%)1 yr', 'Return (%)2 yrs', 'Return (%)3 yrs', 'Return (%)5 yrs', 'Return (%)10 yrs', 'Turnover Ratio (%)', 'No. ofStocks', 'Avg. Market Cap(in Rs. cr)', 'Large Cap(%)', 'Mid Cap(%)', 'Small Cap(%)', 'Highest Sector', 'Avg. Maturity(in yrs)', 'Mod. Duration(in yrs)', 'Yield To Maturity (%)', 'Alpha', 'Sharpe', 'Sortino', 'Beta', 'Standard Deviation', 'classification', 'Exit_load_Remarks']

In [8]:
# Convert Integer Column

df['No. ofStocks'] = pd.to_numeric(df['No. ofStocks'], errors='coerce')
df['No. ofStocks'] = df['No. ofStocks'].fillna(0).astype(int)

In [9]:
# Handle Null Values

for col in float_columns + ['No. ofStocks']:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].median())

categorical_columns = [
    'Funds',
    'Fund Manager',
    'Category',
    'RupeeVestRating',
    'Fund Type',
    'Benchmark Index',
    'Highest Sector',
    'classification',
    'Exit_load_Remarks'
]

for col in categorical_columns:
    if col in df.columns:
        df[col] = df[col].fillna("Unknown")

In [10]:
# Remove Duplicates

df.drop_duplicates(inplace=True)

In [11]:
print(df.dtypes)
df.shape

Funds                                 object
Fund Manager                          object
Category                              object
RupeeVestRating                       object
AUM(in Rs. cr)                       float64
ExpenseRatio (%)                     float64
Fund Type                             object
Inception Date                datetime64[ns]
Benchmark Index                       object
NAV                                  float64
52 WeekHigh (NAV)                    float64
52 WeekLow (NAV)                     float64
Return (%)1 mo                       float64
Return (%)3 mo                       float64
Return (%)6 mo                       float64
Return (%)1 yr                       float64
Return (%)2 yrs                      float64
Return (%)3 yrs                      float64
Return (%)5 yrs                      float64
Return (%)10 yrs                     float64
Turnover Ratio (%)                   float64
No. ofStocks                           int64
Avg. Market Cap(in Rs. cr)           float64
Large Cap(%)                         float64
Mid Cap(%)                           float64
Small Cap(%)                         float64
Highest Sector                        object
Avg. Maturity(in yrs)                float64
Mod. Duration(in yrs)                float64
Yield To Maturity (%)                float64
Alpha                                float64
Sharpe                               float64
Sortino                              float64
Beta                                 float64
Standard Deviation                   float64
classification                        object
Exit_load_Remarks                     object
dtype: object

(1797, 37)

In [12]:
# Save Cleaned Dataset

df.to_csv("cleaned_mutualfund_dataset.csv", index=False)

In [13]:
df.head(10)

,Funds,Fund Manager,Category,RupeeVestRating,AUM(in Rs. cr),ExpenseRatio (%),Fund Type,Inception Date,Benchmark Index,NAV,...,Avg. Maturity(in yrs),Mod. Duration(in yrs),Yield To Maturity (%),Alpha,Sharpe,Sortino,Beta,Standard Deviation,classification,Exit_load_Remarks
0,360 ONE Balanced Hybrid Fund-Reg(G),Mayur Patel,HY-EQ,Unrated,860.1,1.94,Open Ended,2023-09-25,NIFTY 50 Hybrid Composite Debt 50:50 Index,12.45,...,2.930,2.515,7.39,8.27,1.58,2.28,1.20,7.50,Hybrid : Equity Oriented,Nil upto 10% of units and 1% for remaining uni...
1,360 ONE Dynamic Bond Fund-Reg(G),Milan Mody,DT-DYN,2,737.5,0.52,Open Ended,2013-06-24,CRISIL Dynamic Bond Index,21.50,...,6.850,2.515,7.35,3.50,3.72,6.70,0.64,1.45,Debt : Dynamic Bond,Nil
2,360 ONE ELSS Tax Saver Nifty 50 Index Fund-Reg(G),Parijat Garg,EQ-ELSS,Unrated,75.8,0.52,Open Ended,2022-12-28,NIFTY 50 - TRI,13.45,...,3.155,2.515,7.18,1.51,0.47,0.71,0.99,13.90,Equity : Tax Saving (ELSS),Nil
3,360 ONE Flexicap Fund-Reg(G),Mayur Patel,EQ-FLEX,Unrated,1254.2,2.08,Open Ended,2023-06-30,BSE 500 - TRI,15.33,...,3.155,2.515,7.18,16.98,1.40,2.02,0.92,15.45,Equity : Flexi Cap,1% on or before 365D Nil after 365D
4,360 ONE Focused Equity Fund-Reg(G),Mayur Patel,EQ-MLC,4,7305.0,1.78,Open Ended,2014-10-30,BSE 500 - TRI,46.19,...,3.155,2.515,7.18,6.25,0.71,1.00,1.02,16.03,Equity : Multi Cap,1% on or before 12M
5,360 ONE Liquid Fund-Reg(G),Milan Mody,DT-LIQ,1,772.9,0.25,Open Ended,2013-11-13,CRISIL Liquid Debt Index,1945.60,...,0.140,2.515,6.99,1.61,10.39,12.82,0.88,0.16,Debt : Liquid,0.007% for Day 1 0.0065% on Day 2 0.0060% on D...
6,360 ONE Quant Fund-Reg(G),Parijat Garg,EQ-THEM,Unrated,604.7,1.83,Open Ended,2021-11-29,BSE 200 - TRI,18.69,...,3.155,2.515,7.18,12.78,0.96,1.37,1.10,19.17,Equity : Thematic,1% on or before 12M Nil after 12M
7,Aditya Birla SL Active Debt Multi-Mgr FoF(G),Kaustubh Gupta,FOF-DOM,Unrated,10.3,0.54,Open Ended,2006-12-28,CRISIL Composite Bond Index,35.85,...,3.155,2.515,7.18,2.60,2.17,3.78,0.40,1.74,FoFs : Domestic,0.25% on or before 15D Nil after 15D
8,Aditya Birla SL Arbitrage Fund(G),Lovelish Solanki,HY-ARB,3,13843.7,1.01,Open Ended,2009-07-24,Nifty 50 Arbitrage - TRI,25.69,...,1.020,0.660,7.50,3.53,3.35,7.38,-0.08,0.99,Hybrid : Arbitrage,0.25% on or before 15D Nil after 15D
9,Aditya Birla SL Asset Allocator FoF(G),Vinod Narayan Bhat,FOF-DOM,Unrated,187.4,1.25,Open Ended,2006-08-17,CRISIL Hybrid 50+50 - Moderate Index,63.05,...,3.155,2.515,7.18,7.41,1.10,1.54,1.81,11.67,FoFs : Domestic,1% on or before 365D Nil after 365D